name: Deploy Databricks Notebooks

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: "Chekcout"
                uses: actions/checkout@v3

            - name: "Setup CLI"
                uses: databricks/setup-cli@main

            - name: "Login to Databricks"
                run: databricks auth login 

            - name: "Deploy notebooks"
                run: databricks workspace import_dir --overwrite '/notebooks/' '/shared/notebooks/'
