name: "DAB Deployment"

concurrency: 1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy DBX Bundle"
    runs-on: ubuntu-latest
    steps:
      - name: "Chekcout"
        uses: actions/checkout@v3

      - name: "Setup CLI"
        uses: databricks/setup-cli@main

      - name: "Login to Databricks"
        run: databricks auth login 
      
      - run: databricks bundle deploy
        working-directory: . 

        