name: "DBX Deployment"

concurrency: 1

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  deploy:
    name: "Deploy DBX Bundle"
    runs-on: ubuntu-latest
    steps:
      - name: "Chekcout"
        uses: actions/checkout@v3

      - name: "Setup CLI"
        uses: databricks/setup-cli@main
      
      - run: databricks bundle deploy
        working-directory: . 

        